apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: blob-fuse
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: "{resource-group-name}#{account-name}#{container-name}"
    volumeAttributes:
      protocol: fuse
      resourceGroup: blogstorage-rg   # optional, node resource group if it's not provided
      storageAccount: blogsragebmoussaud
      containerName: blob-container 
      AzureStorageAuthType: MSI
      AzureStorageIdentityClientID: "e00991a9-6b80-4132-bd93-1deffef442aa"