apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-container-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: azurefile-pv-container
  storageClassName: azureblob-fuse-premium