apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: azurefile-pv-shared
  storageClassName: azureblob-nfs-premium