apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv-container
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: ${RG}#${STORAGE_ACCOUNT}#${CONTAINER_NAME}
    #volumeHandle: "{resource-group-name}#{account-name}#{container-name}" # i don't if it should be a value like this or the one above
    volumeAttributes:
      resourceGroup: ${RG}
      storageAccount: ${STORAGE_ACCOUNT}
      containername: ${CONTAINER_NAME}
      #useAAD: "true"
      #azureStorageIdentityClientID: ${AZURE_CLIENT_ID}  # Use your managed identity Client ID here