version: '3'
# based on https://learn.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing

env:
  RG: agw4c-rg
  LOCATION: francecentral
  IDENTITY_RESOURCE_NAME: azure-alb-identity
  AGFC_NAME: agw4c-alb
dotenv: ['.env']

tasks:
  azure_auth:
    desc: "Authenticate to Azure using Azure CLI"
    cmds:
      - az login
    silent: false

  azure_config:
    desc: "Configure Azure CLI"
    cmds:
      - az provider register --namespace Microsoft.ContainerService
      - az provider register --namespace Microsoft.Network
      - az provider register --namespace Microsoft.NetworkFunction
      - az provider register --namespace Microsoft.ServiceNetworking
      - az extension add --name alb
  
  create_resource_group:
    desc: "Create a resource group ${RG} in $LOCATION"
    cmds:
      - az group create --name $RG --location $LOCATION
    silent: false
  
  new_aks_cluster:
    desc: create a new AKS cluster
    deps: [create_resource_group]
    cmds:
      - az aks create --resource-group $RG --name agw4c-aks --node-count 1 --network-plugin azure --enable-oidc-issuer --enable-workload-identity --enable-managed-identity --generate-ssh-keys --tier Free --node-vm-size Standard_D4ds_v4
    silent: false

  azure_alb_identity:
    desc: "Install Azure Load Balancer Controller in the AKS cluster"
    deps: [_create_azure_alb_identity, _assign_reader_roler_to_alb_identity, _set_up_federation_with_aks_oidc_issuer]

  deploy_alb_controller:
    desc: "Deploy Azure Load Balancer Controller"
    deps: [aks_get_credentials]
    vars:
      CONTROLLER_NAMESPACE: "azure-alb-system-controller"
      HELM_NAMESPACE: "azure-alb-system-helm"
    cmds:
      - helm install alb-controller oci://mcr.microsoft.com/application-lb/charts/alb-controller --namespace {{.HELM_NAMESPACE}} --version 1.3.7 --set albController.namespace={{.CONTROLLER_NAMESPACE}} --set albController.podIdentity.clientID=$(az identity show -g {{.RG}} -n azure-alb-identity --query clientId -o tsv) --create-namespace 
    silent: false
    
  verify_alb_controller:
    desc: "Verify Azure Load Balancer Controller"
    cmds:
      - kubectl get pods -n azure-alb-system-controller
      - kubectl get gatewayclass azure-alb-external -o yaml
    silent: false

  create_application_gateway4c:
    desc: "Create Application Gateway"
    vars:
      FRONTEND_NAME: frontend
    cmds:
      - az network alb create -g {{.RG}} -n {{.AGFC_NAME}}
      - az network alb show -g {{.RG}} -n {{.AGFC_NAME}}
      - az network alb frontend create -g {{.RG}} -n {{.FRONTEND_NAME}} --alb-name {{.AGFC_NAME}}
      - task: _subnet_to_association_resource
      - task: _peer_vnets
  
  _subnet_to_association_resource:
    desc: "Create subnet and associate it with trafficControllers delegation"
    vars:
      ALB_SUBNET_NAME: subnet-alb
      VNET_NAME: vnet-alb
      ASSOCIATION_NAME: association-test
      principalId:
        sh: az identity show -g {{.RG}} -n {{.IDENTITY_RESOURCE_NAME}} --query principalId -otsv
    cmds:
      - az network vnet create         --name {{.VNET_NAME}} --resource-group {{.RG}}  --address-prefix 10.0.0.0/16 --subnet-name {{.ALB_SUBNET_NAME}} --subnet-prefix 10.0.0.0/24 
      - az network vnet subnet update  --name {{.ALB_SUBNET_NAME}} --resource-group {{.RG}} --vnet-name {{.VNET_NAME}}  --delegations 'Microsoft.ServiceNetworking/trafficControllers'
      - az network vnet subnet list    --resource-group {{.RG}} --vnet-name {{.VNET_NAME}}  --query "[?name=='{{.ALB_SUBNET_NAME}}'].id" --output tsv
      #  Delegate AppGw for Containers Configuration Manager role to RG containing Application Gateway for Containers resource
      - az role assignment create --assignee-object-id {{.principalId}} --assignee-principal-type ServicePrincipal --scope $(az group show --name {{.RG}} --query id -otsv) --role "fbc52c3f-28ad-4303-a892-8a056630b8f1" 
      # Delegate Network Contributor permission for join to association subnet
      - az role assignment create --assignee-object-id {{.principalId}} --assignee-principal-type ServicePrincipal --scope $(az network vnet subnet list  --resource-group {{.RG}} --vnet-name {{.VNET_NAME}}  --query "[?name=='{{.ALB_SUBNET_NAME}}'].id" --output tsv) --role "4d97b98b-1d4f-4787-a291-c67834d212e7" 
      - echo "create the association resource and connect it to the referenced subnet. It can take 5-6 minutes for the Application Gateway for Containers association to be created."
      - az network alb association create -g {{.RG}} -n {{.ASSOCIATION_NAME}} --alb-name {{.AGFC_NAME}} --subnet $(az network vnet subnet list  --resource-group {{.RG}} --vnet-name {{.VNET_NAME}}  --query "[?name=='{{.ALB_SUBNET_NAME}}'].id" --output tsv)

  _peer_vnets:
    desc: peer the AKS VNET with the Application Gateway VNET
    vars:
      nodeResourceGroup:
        sh: az aks show --resource-group {{.RG}} --name agw4c-aks --query nodeResourceGroup --output tsv 
      aksVnetName:
        sh: az network vnet list --resource-group {{.nodeResourceGroup}} -o tsv --query "[0].name"
      aksVnetId:
        sh: az network vnet show --resource-group {{.nodeResourceGroup}} --name {{.aksVnetName}} --query id --output tsv
      appGWVnetId:
        sh: az network vnet show --name vnet-alb --resource-group {{.RG}} -o tsv --query "id"
    cmds:
      - az network vnet peering create --name AppGWtoAKSVnetPeering --resource-group {{.RG}} --vnet-name vnet-alb --remote-vnet {{.aksVnetId}} --allow-vnet-access
      - az network vnet peering create --name AKStoAppGWVnetPeering --resource-group {{.nodeResourceGroup}} --vnet-name {{.aksVnetName}} --remote-vnet {{.appGWVnetId}} --allow-vnet-access

  _create_azure_alb_identity:
    desc: "Create Azure Load Balancer Identity"
    cmds:
      - az identity create --resource-group {{.RG}} --name {{.IDENTITY_RESOURCE_NAME}}
      - az identity show --resource-group {{.RG}} --name {{.IDENTITY_RESOURCE_NAME}}
      - echo "Waiting 60 seconds to allow for replication of the identity..."
      - sleep 60

  _assign_reader_roler_to_alb_identity:
    desc: "Assign Reader role to Azure Load Balancer Identity"
    vars:
      READER_ROLE_ID: "acdd72a7-3385-48ef-bd42-f606fba81ae7"
    cmds:
      - az role assignment create --role {{.READER_ROLE_ID}} --assignee $(az identity show --resource-group {{.RG}} --name {{.IDENTITY_RESOURCE_NAME}} --query principalId -otsv) --scope $(az group show --name {{.RG}} --query id -otsv)

  _set_up_federation_with_aks_oidc_issuer:
    desc: "Set up federation with AKS OIDC issuer"
    cmds:
      - az identity federated-credential create --name "azure-alb-identity" --identity-name {{.IDENTITY_RESOURCE_NAME}} --resource-group {{.RG}} --issuer $(az aks show --resource-group {{.RG}}  --name agw4c-aks --query "oidcIssuerProfile.issuerUrl" -o tsv)  --subject "system:serviceaccount:azure-alb-system:alb-controller-sa"

  list_clusters:
    desc: "List AKS clusters"
    cmds:
      - az aks list --resource-group $RG --output table
    silent: false
  aks_get_credentials:
    desc: "Get credentials for AKS cluster"
    cmds:
      - az aks get-credentials --resource-group $RG --name agw4c-aks
      - kubectl get nodes
    silent: false
  
  deploy_application:
    desc: deploy a sample application
    depends: [aks_get_credentials]
    cmds:
      - kubectl apply -f ./aspnetapp.yaml
      - kubectl get ingress aspnetapp
      - kubectl get service aspnetapp

  clean_up:
    desc: "Clean up"
    cmds:
      - az group delete --name $RG --yes
    silent: false